
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: dataset
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8001:8001"
    # command: uvicorn main:app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    # command: uvicorn main:app

volumes:
  db_data:
  